In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report,accuracy_score
import numpy as np

In [ ]:
df = pd.read_csv("/content/insurance.csv")

In [ ]:
df.head()

   age  weight  height  ...     city  occupation insurance_premium_category
0   67   119.8    1.56  ...   Jaipur     retired                       High
1   36   101.1    1.83  ...  Chennai  freelancer                        Low
2   39    56.8    1.64  ...   Indore  freelancer                        Low
3   22   109.4    1.55  ...   Mumbai     student                     Medium
4   69    62.2    1.60  ...   Indore     retired                       High

[5 rows x 8 columns]

In [ ]:
df.shape

(100, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         100 non-null    int64
 1   weight                      100 non-null    float64
 2   height                      100 non-null    float64
 3   income_lpa                  100 non-null    float64
 4   smoker                      100 non-null    bool
 5   city                        100 non-null    object
 6   occupation                  100 non-null    object
 7   insurance_premium_category  100 non-null    object
dtypes: bool(1), float64(3), int64(1), object(3)
memory usage: 5.7+ KB

In [ ]:
df.isnull().sum()

age                           0
weight                        0
height                        0
income_lpa                    0
smoker                        0
city                          0
occupation                    0
insurance_premium_category    0
dtype: int64

In [ ]:
df["occupation"].unique()

array(['retired', 'freelancer', 'student', 'government_job',
       'business_owner', 'unemployed', 'private_job'], dtype=object)

In [ ]:
df_feat = df.copy()

In [ ]:
df_feat

    age  weight  height  ...       city      occupation insurance_premium_category
0    67   119.8    1.56  ...     Jaipur         retired                       High
1    36   101.1    1.83  ...    Chennai      freelancer                        Low
2    39    56.8    1.64  ...     Indore      freelancer                        Low
3    22   109.4    1.55  ...     Mumbai         student                     Medium
4    69    62.2    1.60  ...     Indore         retired                       High
..  ...     ...     ...  ...        ...             ...                        ...
95   36    52.8    1.57  ...     Indore  business_owner                        Low
96   26   113.8    1.54  ...      Delhi     private_job                        Low
97   52    60.8    1.80  ...  Hyderabad      freelancer                        Low
98   27   101.1    1.82  ...    Kolkata  business_owner                        Low
99   40    70.0    1.59  ...  Bangalore  government_job                        Low

[100 rows x 8 columns]

In [ ]:
#Feature_1
df_feat['bmi'] = df_feat['weight'] /(df_feat['height'] ** 2)

In [ ]:
#Feature_2 : Age_group
def age_group(age):
  if age < 25:
    return "young"
  elif age < 45:
    return "adult"
  elif age < 60:
    return "middle_aged"
  else:
    return "Senior"

In [ ]:
df_feat['Age_group'] = df['age'].apply(age_group)

In [ ]:
# Feature 3: Lifestyle Risk
def lifestyle_risk(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"

In [ ]:
df_feat["lifestyle_risk"] = df_feat.apply(lifestyle_risk, axis=1)

In [ ]:

tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [ ]:
# Feature 4: City Tier
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

In [ ]:
df_feat["city_tier"] = df_feat["city"].apply(city_tier)

In [ ]:
df_feat.drop(columns=['age', 'weight', 'height', 'smoker', 'city'])[['income_lpa', 'occupation', 'bmi', 'Age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']].sample(5)

    income_lpa      occupation  ...  city_tier insurance_premium_category
85    34.66000     private_job  ...          1                        Low
92    30.00000  government_job  ...          2                        Low
33     1.46000         retired  ...          1                     Medium
87    25.59837  government_job  ...          1                        Low
98    28.30000  business_owner  ...          1                        Low

[5 rows x 7 columns]

In [ ]:
df_feat

    age  weight  height  ...    Age_group  lifestyle_risk city_tier
0    67   119.8    1.56  ...       Senior          medium         2
1    36   101.1    1.83  ...        adult          medium         1
2    39    56.8    1.64  ...        adult             low         2
3    22   109.4    1.55  ...        young            high         1
4    69    62.2    1.60  ...       Senior          medium         2
..  ...     ...     ...  ...          ...             ...       ...
95   36    52.8    1.57  ...        adult             low         2
96   26   113.8    1.54  ...        adult          medium         1
97   52    60.8    1.80  ...  middle_aged             low         1
98   27   101.1    1.82  ...        adult          medium         1
99   40    70.0    1.59  ...        adult          medium         1

[100 rows x 12 columns]

In [ ]:
x = df_feat[["bmi", "Age_group", "lifestyle_risk", "city_tier", "income_lpa", "occupation"]]
y = df_feat["insurance_premium_category"]

In [ ]:
X

          bmi    Age_group  ... income_lpa      occupation
0   49.227482       Senior  ...    2.92000         retired
1   30.189017        adult  ...   34.28000      freelancer
2   21.118382        adult  ...   36.64000      freelancer
3   45.535900        young  ...    3.34000         student
4   24.296875       Senior  ...    3.94000         retired
..        ...          ...  ...        ...             ...
95  21.420747        adult  ...   19.64000  business_owner
96  47.984483        adult  ...   34.01000     private_job
97  18.765432  middle_aged  ...   44.86000      freelancer
98  30.521676        adult  ...   28.30000  business_owner
99  27.688778        adult  ...   28.16664  government_job

[100 rows x 6 columns]

In [ ]:
y

0       High
1        Low
2        Low
3     Medium
4       High
       ...
95       Low
96       Low
97       Low
98       Low
99       Low
Name: insurance_premium_category, Length: 100, dtype: object

In [ ]:
categorical_features = ["Age_group", "lifestyle_risk", "occupation", "city_tier"]
numeric_features = ["bmi", "income_lpa"]

In [ ]:
# Create column transformer for OHE
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)

In [ ]:

# Create a pipeline with preprocessing and random forest classifier
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [ ]:
# Split data and train model
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['Age_group',
                                                   'lifestyle_risk',
                                                   'occupation', 'city_tier']),
                                                 ('num', 'passthrough',
                                                  ['bmi', 'income_lpa'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
# Predict and evaluate
y_pred = pipeline.predict(X_test)
accuracy_score(y_test, y_pred)

0.8

In [ ]:
import pickle

# Save the trained pipeline using pickle
pickle_model_path = "model.pkl"
with open(pickle_model_path, "wb") as f:
    pickle.dump(pipeline, f)